using System;

namespace Alveo.UserCode
{
	public enum Marketinfo
	{
		MODE_LOW = 1,
		MODE_HIGH,
		MODE_TIME = 5,
		MODE_BID = 9,
		MODE_ASK,
		MODE_POINT,
		MODE_DIGITS,
		MODE_SPREAD,
		MODE_STOPLEVEL,
		MODE_LOTSIZE,
		MODE_TICKVALUE,
		MODE_TICKSIZE,
		MODE_SWAPLONG,
		MODE_SWAPSHORT,
		MODE_STARTING,
		MODE_EXPIRATION,
		MODE_TRADEALLOWED,
		MODE_MINLOT,
		MODE_LOTSTEP,
		MODE_MAXLOT,
		MODE_SWAPTYPE,
		MODE_PROFITCALCMODE,
		MODE_MARGINCALCMODE,
		MODE_MARGININIT,
		MODE_MARGINMAINTENANCE,
		MODE_MARGINHEDGED,
		MODE_MARGINREQUIRED,
		MODE_FREEZELEVEL
	}
}
