using System;

namespace Alveo.UserCode
{
	[Flags]
	public enum MessageBoxFlags
	{
		MB_OK = 0,
		MB_OKCANCEL = 1,
		MB_ABORTRETRYIGNORE = 2,
		MB_YESNOCANCEL = 3,
		MB_YESNO = 4,
		MB_RETRYCANCEL = 5,
		MB_CANCELTRYCONTINUE = 6,
		MB_ICONSTOP = 7,
		MB_ICONERROR = 8,
		MB_ICONHAND = 16,
		MB_ICONQUESTION = 32,
		MB_ICONEXCLAMATION = 33,
		MB_ICONWARNING = 48,
		MB_ICONINFORMATION = 49,
		MB_ICONASTERISK = 64,
		MB_DEFBUTTON2 = 256,
		MB_DEFBUTTON3 = 512,
		MB_DEFBUTTON4 = 768
	}
}
