using System;

namespace Alveo.UserCode
{
	public enum ObjectProperties
	{
		OBJPROP_TIME1,
		OBJPROP_PRICE1,
		OBJPROP_TIME2,
		OBJPROP_PRICE2,
		OBJPROP_TIME3,
		OBJPROP_PRICE3,
		OBJPROP_COLOR,
		OBJPROP_STYLE,
		OBJPROP_WIDTH,
		OBJPROP_BACK,
		OBJPROP_RAY,
		OBJPROP_ELLIPSE,
		OBJPROP_SCALE,
		OBJPROP_ANGLE,
		OBJPROP_ARROWCODE,
		OBJPROP_TIMEFRAMES,
		OBJPROP_DEVIATION,
		OBJPROP_FONTSIZE = 100,
		OBJPROP_CORNER,
		OBJPROP_XDISTANCE,
		OBJPROP_YDISTANCE,
		OBJPROP_FIBOLEVELS = 200,
		OBJPROP_LEVELCOLOR,
		OBJPROP_LEVELSTYLE,
		OBJPROP_LEVELWIDTH,
		OBJPROP_FIRSTLEVEL = 210
	}
}
